theme: jekyll-theme-cayman

title: MOS Ver.2

exclude:
  - README.md
  - assets/js
  - node_modules
  - vendor
  - Gemfile.lock
  - package.json
  - yarn.lock
  - yarn-error.log

keep_files:
  - assets/js